import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function VelocityChart({ data, height = 200 }) {
    if (data.length === 0) {
        return (_jsx("div", { className: "flex items-center justify-center h-48 text-slate-400 dark:text-slate-500", children: _jsxs("div", { className: "text-center", children: [_jsx("span", { className: "material-symbols-outlined text-4xl mb-2", children: "bar_chart" }), _jsx("p", { className: "text-sm", children: "No sprint data available" })] }) }));
    }
    const maxValue = Math.max(...data.flatMap(d => [d.plannedPoints, d.completedPoints, d.velocity]));
    const scale = maxValue > 0 ? (height - 40) / maxValue : 1;
    return (_jsxs("div", { className: "w-full", children: [_jsxs("div", { className: "relative", style: { height: `${height}px` }, children: [_jsx("div", { className: "absolute inset-0 flex flex-col justify-between pointer-events-none", children: [...Array(5)].map((_, i) => (_jsx("div", { className: "border-b border-slate-100 dark:border-slate-800/50" }, i))) }), _jsxs("div", { className: "absolute left-0 top-0 bottom-8 w-8 flex flex-col justify-between text-[10px] text-slate-400 dark:text-slate-500", children: [_jsx("span", { children: maxValue }), _jsx("span", { children: Math.round(maxValue * 0.75) }), _jsx("span", { children: Math.round(maxValue * 0.5) }), _jsx("span", { children: Math.round(maxValue * 0.25) }), _jsx("span", { children: "0" })] }), _jsx("div", { className: "absolute left-10 right-0 top-0 bottom-8 flex items-end justify-around gap-2 px-2", children: data.map((item, index) => (_jsxs("div", { className: "flex-1 flex flex-col items-center group relative", children: [_jsxs("div", { className: "flex items-end gap-0.5 h-full", children: [_jsx("div", { className: "w-3 bg-slate-200 dark:bg-slate-700 rounded-t transition-all duration-500 ease-out hover:bg-slate-300 dark:hover:bg-slate-600", style: {
                                                height: `${item.plannedPoints * scale}px`,
                                                animationDelay: `${index * 100}ms`,
                                            } }), _jsx("div", { className: "w-3 bg-gradient-to-t from-emerald-500 to-emerald-400 dark:from-emerald-600 dark:to-emerald-500 rounded-t transition-all duration-500 ease-out shadow-sm hover:from-emerald-600 hover:to-emerald-500", style: {
                                                height: `${item.completedPoints * scale}px`,
                                                animationDelay: `${index * 100 + 50}ms`,
                                            } })] }), _jsx("div", { className: "absolute bottom-full mb-2 hidden group-hover:block z-10", children: _jsxs("div", { className: "bg-slate-900 dark:bg-slate-700 text-white text-xs rounded-lg px-3 py-2 shadow-xl whitespace-nowrap", children: [_jsx("div", { className: "font-bold mb-1", children: item.sprintName }), _jsxs("div", { className: "flex items-center gap-2 text-slate-300", children: [_jsx("span", { className: "inline-block w-2 h-2 rounded-full bg-slate-400" }), _jsxs("span", { children: ["Planned: ", item.plannedPoints, " pts"] })] }), _jsxs("div", { className: "flex items-center gap-2 text-emerald-400", children: [_jsx("span", { className: "inline-block w-2 h-2 rounded-full bg-emerald-500" }), _jsxs("span", { children: ["Completed: ", item.completedPoints, " pts"] })] }), _jsx("div", { className: "flex items-center gap-2 text-blue-400 mt-1 pt-1 border-t border-slate-700 dark:border-slate-600", children: _jsxs("span", { className: "font-medium", children: ["Velocity: ", item.velocity] }) }), _jsx("div", { className: "absolute bottom-0 left-1/2 -translate-x-1/2 translate-y-full", children: _jsx("div", { className: "w-0 h-0 border-l-4 border-r-4 border-t-4 border-transparent border-t-slate-900 dark:border-t-slate-700" }) })] }) })] }, index))) }), _jsx("div", { className: "absolute left-10 right-0 bottom-0 h-8 flex justify-around text-[10px] text-slate-500 dark:text-slate-400 font-medium", children: data.map((item, index) => (_jsx("div", { className: "flex-1 text-center truncate px-1", children: item.sprintName }, index))) })] }), _jsxs("div", { className: "flex items-center justify-center gap-6 mt-4 text-xs", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-3 h-3 rounded-sm bg-slate-200 dark:bg-slate-700" }), _jsx("span", { className: "text-slate-600 dark:text-slate-400", children: "Planned" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-3 h-3 rounded-sm bg-gradient-to-t from-emerald-500 to-emerald-400" }), _jsx("span", { className: "text-slate-600 dark:text-slate-400", children: "Completed" })] })] })] }));
}
